model_list:
  - model_name: mini
    litellm_params:
      model: github_copilot/gpt-4o-mini
  - model_name: haiku
    litellm_params:
      model: claude-code/haiku
  - model_name: sonnet
    litellm_params:
      model: claude-code/sonnet
  - model_name: opus
    litellm_params:
      model: claude-code/opus

litellm_settings:
  custom_provider_map:
    - { "provider": "claude-code", "custom_handler": handlers.claude.claude_code }
